### ISSUE TITLE
Call to subprocess.check_call always fails with “[Errno 2] No such file or directory”

### ISSUE THREAD

**Issue by kugland** [estheruary/ansible-plugin-systemd_escape#3]
Call to `subprocess.check_call` always fails with `[Errno 2] No such file
or directory` because the command line is passed as a single string, even
though the `shell=` parameter is not set to `True`.

Since the call to `systemd-escape` doesn’t require any advanced shell
feature, it should suffice to make the `args` parameter an array.

**Comment by kugland** [comment]
#1 will fix this.

**Comment by estheruary** [comment]
Merged! Sorry, it took so long. Had no anyone other than me used it.
